receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
      lightstep-access-token: ${env:LS_ACCESS_TOKEN}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]