service: thing
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-west-1:184161586896:layer:opentelemetry-collector-amd64-0_1_0:1
    environment:
      OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/config.yaml
      LS_ACCESS_TOKEN: <access token>

plugins:
  - serverless-python-requirements
